services:
  php:
    build:
      context: docker/php
    security_opt:
      - label=disable
    volumes:
      - ./app:/app
    environment:
      APP_ENV: dev
      MONGO_URL: mongodb://mongodb:27017/sidegigs
      REDIS_URL: redis://redis:6379
      MAILER_DSN: smtp://mailpit:1025
      APP_SECRET: change_this_in_production
    depends_on:
      - mongodb
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/app:ro,z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - php

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sidegigs
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongodb_data:
  redis_data:
