server {
    listen 80 default_server;
    listen [::]:80 default_server;


    root /var/www/sms/app/public;
    index index.php;

    access_log  /var/log/nginx/sms.access.log;
    error_log   /var/log/nginx/sms.error.log;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass   unix:/run/php-fpm83/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param  DOCUMENT_ROOT    $realpath_root;
        fastcgi_param  SERVER_NAME      $host;
        fastcgi_param  APP_ENV          prod;
        fastcgi_param  APP_DEBUG        0;
        internal;
    }

 #   location ~ \.php$ {
 #       return 404;
 #   }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|css|js|woff2?|ttf|eot|map)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        log_not_found off;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ /(var|config|src|vendor|translations|tests)/ {
        deny all;
        access_log off;
        log_not_found off;
    }
}
